name: "[CI] anaconda-assistant-sdk"

on:
  pull_request:
    branches:
      - main
    paths:
    - .github/workflows/ci-anaconda-assistant-sdk.yml
    - libs/anaconda-assistant-sdk/**
  push:
    branches:
      - main
    paths:
    - .github/workflows/ci-anaconda-assistant-sdk.yml
    - libs/anaconda-assistant-sdk/**
    tags:
    - anaconda-assistant-sdk-v[0-9]+.[0-9]+.[0-9]+*
  merge_group:

defaults:
  run:
    working-directory: ./libs/anaconda-assistant-sdk

jobs:
  test:
    name: Test, Python ${{ matrix.python-version }}
    runs-on:
      labels: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install testing dependencies
        env:
          TOKEN: ${{ secrets.ANACONDA_ORG_DOWNLOAD_TOKEN }}
        run: |
          python -m pip config set global.extra-index-url "https://pypi.anaconda.org/t/$TOKEN/anaconda-cloud/label/dev/simple"
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox

  build-conda-package:
    name: Build conda package
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
          with:
            fetch-depth: 0
        - name: Create build environment
          run: |
            source $CONDA/bin/activate
            conda create -n build --file ../../etc/build.linux-64.lock
        - name: conda build
          run: |
            source $CONDA/bin/activate && conda activate build
            VERSION=`hatch version` conda build -c t/${{ secrets.ANACONDA_ORG_DOWNLOAD_TOKEN }}/anaconda-cloud -c conda-forge -c defaults --override-channels conda.recipe
            mv $CONDA_PREFIX/conda-bld .
        - name: Upload the build artifact
          uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
          with:
            name: anaconda-assistant-sdk-conda-${{ github.sha }}
            path: libs/anaconda-assistant-sdk/conda-bld
            if-no-files-found: error
            retention-days: 7

  build-wheel:
    name: Build the wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: "3.10"
      - name: Install build dependencies
        run: pip install build
      - name: Build the package
        run: python -m build
      - name: Upload the build artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: anaconda-assistant-sdk-wheel-${{ github.sha }}
          path: libs/anaconda-assistant-sdk/dist/*
          if-no-files-found: error
          retention-days: 7

  # This check job runs to ensure all tests and builds  have passed, such that we can use it as a "wildcard"
  # for branch protection to ensure all tests pass before a PR can be merged.
  check:
    name: Check all tests passed
    if: always()
    needs: [test, build-conda-package, build-wheel]
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all required jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

  publish-conda-pkg-to-anaconda-dot-org:
    name: Publish conda package to Anaconda.org
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run on push to main branch
    needs: [check]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      with:
        fetch-depth: 0
    - name: Create build environment
      run: |
        source $CONDA/bin/activate
        conda create -n build --file ../../etc/build.linux-64.lock
    - name: Download the build artifacts
      uses: actions/download-artifact@9c19ed7fe5d278cd354c7dfd5d3b88589c7e2395 # v4
      with:
        name: anaconda-assistant-sdk-conda-${{ github.sha }}
        path: ~/anaconda-assistant-sdk-conda-bld
    - name: publish
      env:
        TOKEN: ${{ secrets.ANACONDA_ORG_UPLOAD_TOKEN }}
      run: |
        source $CONDA/bin/activate && conda activate build
        [[ "$GITHUB_REF" =~ ^refs/tags/anaconda-assistant-sdk-v ]] || export LABEL="--label dev"
        anaconda --verbose \
          --token $TOKEN \
          upload \
          --user anaconda-cloud \
          $LABEL \
          --force \
          ~/anaconda-assistant-sdk-conda-bld/noarch/anaconda-assistant-sdk-*

  publish-wheel-to-anaconda-dot-org:
    name: Publish wheel to Anaconda.org
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run on push to main branch
    needs: [check]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      with:
        fetch-depth: 0
    - name: Download the build artifacts
      uses: actions/download-artifact@9c19ed7fe5d278cd354c7dfd5d3b88589c7e2395 # v4
      with:
        name: anaconda-assistant-sdk-wheel-${{ github.sha }}
        path: ~/dist
    - name: Upload to anaconda.org
      env:
        TOKEN: ${{ secrets.ANACONDA_ORG_UPLOAD_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/bin/activate
        conda install -y anaconda-client
        [[ "$GITHUB_REF" =~ ^refs/tags/anaconda-assistant-sdk-v ]] || export LABEL="--label dev"
        anaconda --verbose \
          --token $TOKEN \
          upload \
          --user anaconda-cloud \
          ~/dist/*.whl \
          --summary \
          "The Anaconda Assistant Python SDK" \
          $LABEL \
          --force

  publish-to-pypi:
    name: Publish to PyPI
    # Only publish to PyPI if a tagged release
    if: startsWith(github.event.ref, 'refs/tags/anaconda-assistant-sdk-v')
    runs-on: ubuntu-latest
    needs: [check]
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
    - name: Download the build artifacts
      uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4
      with:
        name: anaconda-assistant-sdk-wheel-${{ github.sha }}
        path: libs/anaconda-assistant-sdk/dist
    - name: Install build dependencies
      run: pip install hatch
    - name: Upload to PyPI
      run: hatch publish ./dist
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_SDK_TOKEN }}
